"""Sparse-PCE regression against unmodified UQLab 2.2.0 and analytic cases."""

import json
from dataclasses import FrozenInstanceError
from pathlib import Path

import numpy as np
import pytest
from scipy.stats import norm, qmc

from pystra.active_learning._pce import _fit_ols, _hermite_basis, _multi_indices
from pystra.active_learning import PCESurrogate

REFERENCE = json.loads(
    (Path(__file__).parent / "data/uqlab_sparse_pce.json").read_text()
)


@pytest.mark.parametrize("case", REFERENCE["cases"], ids=lambda case: case["name"])
def test_uqlab_numerical_references(case):
    # Fixture regenerated by scripts/validate_uqlab_pce.m with the installed
    # original UQLab kernels under Octave. Common uniformly drawn bootstrap
    # indices remove RNG differences (and UQLab's endpoint-weighting bug).
    surrogate = PCESurrogate(
        degree=case["degrees"],
        q_norm=case["q_norms"],
        degree_early_stop=False,
        q_norm_early_stop=False,
        n_bootstrap=case["n_bootstrap"],
        seed=case["bootstrap_seed"],
    )
    surrogate.fit(case["points"], case["values"])
    actual, expected = surrogate.fit_result, case["expected"]
    assert actual.degree == expected["degree"]
    assert actual.q_norm == expected["q_norm"]
    actual_terms = dict(zip(actual.indices, actual.coefficients))
    expected_terms = dict(
        zip(map(tuple, expected["indices"]), expected["coefficients"])
    )
    assert actual_terms.keys() == expected_terms.keys()
    for powers in expected_terms:
        assert actual_terms[powers] == pytest.approx(expected_terms[powers], abs=2e-10)
    assert actual.loo_error == pytest.approx(expected["loo_error"], rel=2e-6, abs=1e-12)
    assert actual.corrected_loo_error == pytest.approx(
        expected["corrected_loo_error"], rel=2e-6, abs=1e-12
    )
    mean, std = surrogate.predict(case["query"])
    np.testing.assert_allclose(mean, expected["mean"], rtol=1e-9, atol=2e-10)
    np.testing.assert_allclose(std, expected["std"], rtol=1e-8, atol=2e-10)


def test_press_agrees_with_explicit_deletions_and_correction():
    points = np.random.default_rng(42).normal(size=(25, 2))
    indices = _multi_indices(2, 2, 1, 2, 100)
    basis = _hermite_basis(points, indices)
    values = np.exp(0.3 * points[:, 0]) + points[:, 1]
    fitted = _fit_ols(basis, values)
    residuals = []
    for row in range(len(points)):
        keep = np.arange(len(points)) != row
        coefficients = np.linalg.lstsq(basis[keep], values[keep], rcond=None)[0]
        residuals.append(values[row] - basis[row] @ coefficients)
    loo = np.mean(np.asarray(residuals) ** 2) / np.var(values)
    assert fitted.loo == pytest.approx(loo, rel=1e-9)
    correction = (
        len(points)
        / (len(points) - len(indices))
        * (1 + np.trace(np.linalg.inv(basis.T @ basis)))
    )
    assert fitted.corrected_loo == pytest.approx(loo * correction, rel=1e-9)


def test_hyperbolic_interaction_truncation_and_basis_budget():
    indices = _multi_indices(5, 4, 0.5, 2, 200)
    assert np.all(np.sum(np.sqrt(indices), axis=1) <= 2 + 1e-12)
    assert np.all(np.count_nonzero(indices, axis=1) <= 2)
    assert len(set(map(tuple, indices))) == len(indices)
    assert (1, 1, 0, 0, 0) in set(map(tuple, indices))
    assert (2, 1, 0, 0, 0) not in set(map(tuple, indices))
    with pytest.raises(ValueError, match="max_terms"):
        _multi_indices(20, 8, 1, 20, 100)


def test_underdetermined_dictionary_recovers_sparse_polynomial():
    rng = np.random.default_rng(22)
    points = rng.normal(size=(55, 5))
    values = 1 + points[:, 0] + 0.15 * (points[:, 1] ** 2 - 1) * points[:, 2]
    surrogate = PCESurrogate(degree=(1, 2, 3, 4), seed=5, degree_early_stop=False)
    surrogate.fit(points, values)
    result = surrogate.fit_result
    assert result.degree == 3
    assert len(result.indices) == 3
    assert any(candidate.n_candidates > len(points) for candidate in result.candidates)
    query = rng.normal(size=(200, 5))
    mean, std = surrogate.predict(query)
    np.testing.assert_allclose(
        mean, 1 + query[:, 0] + 0.15 * (query[:, 1] ** 2 - 1) * query[:, 2], atol=1e-11
    )
    assert std.max() < 1e-11


def test_refitting_readapts_degree_and_preserves_snapshot():
    points = np.random.default_rng(2).normal(size=(80, 2))
    surrogate = PCESurrogate(degree=(1, 2, 3, 4), seed=4, degree_early_stop=False)
    surrogate.fit(points, 2 + points[:, 0])
    first = surrogate.fit_result
    assert first.degree == 1
    surrogate.fit(points, 2 + points[:, 0] + 0.3 * points[:, 1] ** 3)
    assert surrogate.fit_result.degree == 3
    assert first.degree == 1
    with pytest.raises(FrozenInstanceError):
        first.degree = 9
    with pytest.raises(ValueError):
        surrogate.fit(points, np.full(80, np.nan))
    assert surrogate.fit_result is None
    with pytest.raises(RuntimeError):
        surrogate.predict(points)


def test_degree_early_stop_can_be_disabled_for_isolated_high_order_terms():
    # Exactly symmetric design makes an isolated even high-order response
    # difficult to discover after lower-degree candidates cease improving.
    points = norm.ppf(qmc.LatinHypercube(2, seed=3).random(80))
    values = 2 + points[:, 0] + 0.1 * (points[:, 1] ** 4 - 6 * points[:, 1] ** 2 + 3)
    exhaustive = PCESurrogate(degree=(1, 2, 3, 4, 5), degree_early_stop=False, seed=1)
    exhaustive.fit(points, values)
    assert exhaustive.fit_result.degree == 4
    assert (
        len({candidate.degree for candidate in exhaustive.fit_result.candidates}) == 5
    )
    np.testing.assert_allclose(exhaustive.predict(points)[0], values, atol=1e-10)


@pytest.mark.parametrize(
    "kwargs",
    [
        {"degree": []},
        {"degree": (2, 1)},
        {"degree": True},
        {"q_norm": 0},
        {"q_norm": (1, 0.5)},
        {"q_norm": np.nan},
        {"method": "lasso"},
        {"max_interaction": 0},
        {"max_terms": 0},
        {"degree_early_stop": 1},
    ],
)
def test_sparse_configuration_validation(kwargs):
    with pytest.raises(ValueError):
        PCESurrogate(**kwargs)


def test_constant_and_dependent_designs_stay_identifiable():
    points = np.random.default_rng(1).normal(size=(50, 2))
    points[:, 1] = points[:, 0]
    surrogate = PCESurrogate(seed=1)
    surrogate.fit(points, np.ones(50) * 3)
    assert len(surrogate.fit_result.indices) == 1
    mean, spread = surrogate.predict(points)
    np.testing.assert_allclose(mean, 3, atol=1e-12)
    assert spread.max() < 1e-12
    surrogate.fit(points, 1 + points[:, 0])
    assert len(surrogate.fit_result.indices) == 2
    np.testing.assert_allclose(
        surrogate.predict(points)[0], 1 + points[:, 0], atol=1e-12
    )


def test_rank_deficient_bootstrap_uses_minimum_norm_and_reports_count():
    points = np.random.default_rng(6).normal(size=(8, 2))
    values = np.exp(points[:, 0]) + points[:, 1]
    surrogate = PCESurrogate(method="ols", degree=2, n_bootstrap=30, seed=3)
    surrogate.fit(points, values)
    result = surrogate.fit_result
    assert result.n_rank_deficient_bootstrap > 0
    # Include every uniform resample, including unidentifiable ones, exactly
    # as UQLab's least-squares bootstrap. No conditioning on full rank.
    basis = _hermite_basis(points, np.asarray(result.indices))
    predictions = []
    rng = np.random.default_rng(3)
    for _ in range(30):
        rows = rng.integers(len(points), size=len(points))
        coefficients = np.linalg.pinv(basis[rows]) @ values[rows]
        predictions.append(basis @ coefficients)
    np.testing.assert_allclose(
        surrogate.predict(points)[1], np.std(predictions, axis=0, ddof=1), rtol=1e-10
    )
