"""Generate the installed script converter's data from the reviewed API manifest."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate() -> str:
    """Return deterministic Python data; no checkout data is needed at runtime."""
    manifest = json.loads((ROOT / "docs/migration/api-migration.json").read_text())
    entries = {entry["old"]: entry for entry in manifest["definitions"]}
    settings = manifest["script_converter"]
    symbols = {}
    for old, entry in entries.items():
        if entry["kind"] != "class":
            continue
        target = entry["current"]
        if target is None and "Identical" in entry.get("notes", ""):
            target = entry["replacements"][0]
        manual = target is None or any(
            word in old for word in ("Calibration", "GenericModel", "AnalysisOptions")
        )
        constructor = entries.get(old + ".__init__", {})
        record = {
            "target": target,
            "public_path": settings["current_public_classes"].get(target, target),
            "keywords": constructor.get("keyword_renames", {}),
            "manual": manual,
            "positional_limit": constructor.get("positional_limit", 1000),
        }
        symbols[old] = record
        if target:
            symbols.setdefault(target, {**record, "target": target})
    for module, names in settings["public_imports"].items():
        for name, path in names.items():
            if path in symbols:
                symbols[f"{module}.{name}"] = symbols[path]
    # Current public spellings also resolve after the first conversion.
    for old, entry in list(symbols.items()):
        if entry["target"]:
            parent = old.rsplit(".", 1)[0]
            name = entry["target"].rsplit(".", 1)[1]
            symbols.setdefault(f"{parent}.{name}", entry)
    methods = {}
    for old, entry in entries.items():
        name = old.rsplit(".", 1)[1]
        if entry["kind"] == "callable" and not name.startswith("_"):
            target = entry["current"]
            if target is None or name != target.rsplit(".", 1)[1]:
                methods.setdefault(name, set()).update(
                    entry.get("replacements", []) or ([target] if target else [])
                )
    data = {
        "modules": settings["module_paths"],
        "private_modules": settings["private_modules"],
        "symbols": symbols,
        "methods": {name: sorted(paths) for name, paths in methods.items()},
    }
    return (
        '"""Generated by scripts/generate_migration_data.py; do not edit."""\n\n'
        'import json\n\nDATA = json.loads(r"""\n'
        + json.dumps(data, sort_keys=True, indent=2)
        + '\n""")\n'
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "src/pystra/migrate/_data.py"
    content = generate()
    if args.check:
        if not path.exists() or path.read_text() != content:
            print(
                "Migration converter data is stale; run scripts/generate_migration_data.py"
            )
            return 1
        print("Migration converter data agrees with api-migration.json")
    else:
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
